os: linux
dist: xenial
language: python

python:
  - "3.7"

jobs:
  include:
    - name: "Python 3.7 on Linux Ubuntu"
      python: 3.7

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -e .[tests]
  - pip install coveralls

script:
  - black -S -t py37 --check mce_azure
  - pytest

after_script:
  - coveralls

